#! /bin/bash
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr_342 2007-08-01
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr_450 2008-06-01 
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr_600 2003-07-01
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr_800 2008-06-01
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr_1070 2003-03-01
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr1_2  2002-02-14
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr2_3  2008-08-01
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr4_6  2007-10-06
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr8_10 2007-06-15
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr12_18 2003-11-10
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr18_26 2003-09-19
runhaskell UpdateReceiverTemperatures.lhs $1 RcvrArray18_26 2010-03-08
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr26_40 2007-09-01
runhaskell UpdateReceiverTemperatures.lhs $1 Rcvr40_52 2008-11-01
#runhaskell UpdateReceiverTemperatures.lhs $1 

# Notes:

#| receiver       | date       |  notes

#| RcvrPF_1       | 2008-06-01 | DSS: Rcvr_450, Rcvr_800
#| RcvrPF_1       | 2007-08-01 | DSS: Rcvr_342
#| RcvrPF_1       | 2003-07-01 | DSS: Rcvr_600
#| RcvrPF_2       | 2003-03-01 | DSS: Rcvr_1070
#| Rcvr1_2        | 2002-02-14 | 2005-05-27 has all 1.0's.; done
#| Rcvr2_3        | 2008-08-01 | done
#| Rcvr4_6        | 2007-10-06 | done
#| Rcvr8_10       | 2007-06-15 | 2009-07-26 has all 1.0's; done
#| Rcvr12_18      | 2003-11-10 | 2009-07-23 has all 1.0's; done
#| Rcvr18_26      | 2003-09-19 | 2005-05-27 has all 1.0's; done
#| RcvrArray18_26 | 2010-03-08 | done
#| Rcvr26_40      | 2007-09-01 | done
#| Rcvr40_52      | 2008-11-01 | 2009-11-21 has all 1.0's; done

#Not in Measurement:
#Holography
#NoiseSource
#Rcvr_PAR use 120 K.
#Rcvr_RRI

