#! /bin/bash
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr_342       2007-08-01
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr_450       2008-06-01 
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr_600       2003-07-01
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr_800       2008-06-01
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr_1070      2003-03-01
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr1_2        2002-02-14
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr2_3        2008-08-01
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr4_6        2007-10-06
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr8_10       2007-06-15
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr12_18      2003-11-10
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr18_26      2003-09-19
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 RcvrArray18_26 2010-03-08
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr26_40      2007-09-01
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr40_52      2008-11-01
# we are faking these receiver temperatures, so the date is irrelevant
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr_PAR       2010-01-01 
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr_RRI       2010-01-01 
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Holography     2010-01-01 
runhaskell Antioch/UpdateReceiverTemperatures.lhs $1 Rcvr68_92     2010-01-01 

# Notes:        TBF what does this table signify?
# Here is the mapping that the above calls produce between the
# receivers as the MySql DB of rcvr temps thinks of them
# and the DSS receivers used.  The date specifies the date used (same
# as above).  If this is *not* the most recent set of temperatures, there's 
# a good reason why we're not using that most recent set - that's 
# explained in the notes column.

#| receiver       | date       |  notes

#| RcvrPF_1       | 2008-06-01 | DSS: Rcvr_450, Rcvr_800
#| RcvrPF_1       | 2007-08-01 | DSS: Rcvr_342
#| RcvrPF_1       | 2003-07-01 | DSS: Rcvr_600
#| RcvrPF_2       | 2003-03-01 | DSS: Rcvr_1070
#| Rcvr1_2        | 2002-02-14 | 2005-05-27 has all 1.0's.
#| Rcvr2_3        | 2008-08-01 | 
#| Rcvr4_6        | 2007-10-06 | 
#| Rcvr8_10       | 2007-06-15 | 2009-07-26 has all 1.0's
#| Rcvr12_18      | 2003-11-10 | 2009-07-23 has all 1.0's
#| Rcvr18_26      | 2003-09-19 | 2005-05-27 has all 1.0's
#| RcvrArray18_26 | 2010-03-08 | 
#| Rcvr26_40      | 2007-09-01 | 
#| Rcvr40_52      | 2008-11-01 | 2009-11-21 has all 1.0's

#Not in Measurement - here, we explain what UpdateReceiverTemperatures
# will put in for these:
#NoiseSource   (not used)
#Zpectrometer  (not used)
#Holography    (11.7,1e6),(12.2,1e6)
#Rcvr_PAR      (80.0,120.0),(100.0,120.0)
#Rcvr_RRI      (0.1,300.0),(1.6,300.0)

